import React, { useState, useEffect } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { donationsApi, donorsApi } from '../api';
import type { Donation, Donor } from '../types';
import { X, Save, Calendar, DollarSign, Mail, Phone, Briefcase, Search, User, ChevronDown, Loader2 } from 'lucide-react';

interface DonationFormProps {
  donation?: Donation | null;
  onClose: () => void;
  onSuccess: () => void;
}

const DonationForm = ({ donation, onClose, onSuccess }: DonationFormProps) => {
  const [formData, setFormData] = useState({
    donor_id: '',
    donor_name: '',
    donor_email: '',
    donor_phone: '',
    amount: '',
    type: 'cash' as 'cash' | 'goods',
    description: '',
    date_received: '',
    receipt_no: '',
  });
  const [donorSearch, setDonorSearch] = useState('');
  const [showDonorDropdown, setShowDonorDropdown] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const { data: donorResultsData, isFetching: isFetchingDonors } = useQuery({
    queryKey: ['donors-search', donorSearch],
    queryFn: () => donorsApi.getAll({ search: donorSearch }),
    enabled: donorSearch.length > 1 && showDonorDropdown,
    placeholderData: previousData => previousData,
  });

  const donorResults = Array.isArray(donorResultsData) ? donorResultsData : (donorResultsData?.data || []);

  useEffect(() => {
    if (donation) {
      setFormData({
        donor_id: donation.donor_id?.toString() || '',
        donor_name: donation.donor_name,
        donor_email: donation.donor_email || '',
        donor_phone: donation.donor_phone || '',
        amount: donation.amount.toString(),
        type: donation.type,
        description: donation.description || '',
        date_received: new Date(donation.date_received).toISOString().split('T')[0],
        receipt_no: donation.receipt_no,
      });
      setDonorSearch(donation.donor_name);
    } else {
      // Set default date to today for new donations
      setFormData({
        donor_id: '',
        donor_name: '',
        donor_email: '',
        donor_phone: '',
        amount: '',
        type: 'cash' as 'cash' | 'goods',
        description: '',
        date_received: new Date().toISOString().split('T')[0],
        receipt_no: '', // Will be generated automatically
      });
      setDonorSearch('');
    }
  }, [donation]);

  const handleDonorSelect = (donor: Donor) => {
    setFormData({
      ...formData,
      donor_id: donor.id.toString(),
      donor_name: donor.name,
      donor_email: donor.email || '',
      donor_phone: donor.phone || '',
    });
    setDonorSearch(donor.name);
    setShowDonorDropdown(false);
  };

  const handleDonorInputClick = () => {
    setShowDonorDropdown(true);
  };

  const handleDonorInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setDonorSearch(value);
    setFormData({ ...formData, donor_name: value });
    if (value.length > 1) {
      setShowDonorDropdown(true);
    }
  };

  const createMutation = useMutation({
    mutationFn: donationsApi.create,
    onSuccess: onSuccess,
  });

  const updateMutation = useMutation({
    mutationFn: (data: Partial<Donation>) => donationsApi.update(donation!.id, data),
    onSuccess: onSuccess,
  });

    const handleSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      const newErrors: Record<string, string> = {};

      if (!formData.donor_name.trim()) newErrors.donor_name = 'Nama donatur wajib diisi';
      if (!formData.amount.trim() || parseFloat(formData.amount) <= 0) newErrors.amount = 'Jumlah donation harus lebih dari 0';
      if (!formData.date_received) newErrors.date_received = 'Tanggal terima wajib';

      setErrors(newErrors);
      if (Object.keys(newErrors).length > 0) return;

      const donationData: Partial<Donation> = {
        donor_id: formData.donor_id ? parseInt(formData.donor_id) : undefined,
        donor_name: formData.donor_name,
        donor_email: formData.donor_email || undefined,
        donor_phone: formData.donor_phone || undefined,
        amount: parseFloat(formData.amount),
        type: formData.type,
        description: formData.description || undefined,
        date_received: formData.date_received,
        // receipt_no will be generated by backend if not provided
      };

      if (donation) {
        await updateMutation.mutateAsync(donationData);
      } else {
        await createMutation.mutateAsync(donationData);
      }
      onSuccess();
    };

  const isLoading = createMutation.isPending || updateMutation.isPending;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-2xl max-w-xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6 border-b">
          <div className="flex justify-between items-center">
            <h2 className="text-2xl font-bold">
              {donation ? 'Edit' : 'Tambah'} Donasi
            </h2>
            <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg">
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Donatur *</label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <input
                  type="text"
                  value={donorSearch}
                  onChange={handleDonorInputChange}
                  onFocus={handleDonorInputClick}
                  className={`w-full pl-10 p-3 pr-10 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all ${
                    errors.donor_name ? 'border-red-500' : 'border-gray-300'
                  }`}
                  placeholder="Cari nama donor atau ketik baru..."
                />
                <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none" />
                {showDonorDropdown && (
                  <div className="absolute z-20 w-full mt-1 bg-white border border-gray-300 rounded-xl shadow-lg max-h-60 overflow-auto">
                    {isFetchingDonors && (
                      <div className="p-4 text-center text-gray-500 flex items-center gap-2">
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Mencari...
                      </div>
                    )}
                    {donorResults.length === 0 && !isFetchingDonors && donorSearch.length > 1 && (
                      <div className="p-4 text-gray-500 text-sm text-center">
                        Donor tidak ditemukan
                      </div>
                    )}
                    {donorResults.map((d: Donor) => (
                      <button
                        key={d.id}
                        type="button"
                        onClick={() => handleDonorSelect(d)}
                        className="w-full text-left p-3 hover:bg-gray-50 border-b border-gray-100 last:border-b-0 flex items-center gap-3"
                      >
                        <div className="font-medium text-gray-900">{d.name}</div>
                        <div className="text-sm text-gray-500">{d.email || d.phone || 'Tanpa kontak'}</div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
              {errors.donor_name && <p className="text-red-500 text-sm mt-1">{errors.donor_name}</p>}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Email Donatur</label>
              <input
                type="email"
                value={formData.donor_email}
                onChange={(e) => setFormData({ ...formData, donor_email: e.target.value })}
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                placeholder="email@donatur.com"
                disabled
              />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Telepon Donatur</label>
              <input
                type="tel"
                value={formData.donor_phone}
                onChange={(e) => setFormData({ ...formData, donor_phone: e.target.value })}
                className={`w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all ${
                  errors.donor_phone ? 'border-red-500' : 'border-gray-300'
                }`}
                placeholder="Nomor telepon donatur"
              />
              {errors.donor_phone && <p className="text-red-500 text-sm mt-1">{errors.donor_phone}</p>}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Jenis Donasi *</label>
              <select
                value={formData.type}
                onChange={(e) => setFormData({ ...formData, type: e.target.value as 'cash' | 'goods' })}
                className={`w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all ${
                  errors.type ? 'border-red-500' : 'border-gray-300'
                }`}
                required
              >
                <option value="cash">Uang Tunai</option>
                <option value="goods">Barang</option>
              </select>
              {errors.type && <p className="text-red-500 text-sm mt-1">{errors.type}</p>}
            </div>
          </div>

          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Jumlah Donasi *</label>
              <div className="relative">
                <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <input
                  type="number"
                  value={formData.amount}
                  onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                  className={`w-full pl-10 p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all ${
                    errors.amount ? 'border-red-500' : 'border-gray-300'
                  }`}
                  min="0.01"
                  step="0.01"
                  placeholder="Jumlah dalam rupiah"
                  required
                />
              </div>
              {errors.amount && <p className="text-red-500 text-sm mt-1">{errors.amount}</p>}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Tanggal Terima *</label>
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <input
                  type="date"
                  value={formData.date_received}
                  onChange={(e) => setFormData({ ...formData, date_received: e.target.value })}
                  className={`w-full pl-10 p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all ${
                    errors.date_received ? 'border-red-500' : 'border-gray-300'
                  }`}
                  required
                />
              </div>
              {errors.date_received && <p className="text-red-500 text-sm mt-1">{errors.date_received}</p>}
            </div>
          </div>

          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Keterangan</label>
              <textarea
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all resize-vertical"
                rows={3}
                placeholder="Catatan tambahan tentang donasi..."
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Nomor Resi (Opsional)</label>
              <input
                type="text"
                value={formData.receipt_no}
                onChange={(e) => setFormData({ ...formData, receipt_no: e.target.value })}
                className="w-full p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                placeholder="Nomor resi akan di-generate otomatis jika kosong"
              />
            </div>
          </div>

          <div className="flex gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-800 font-medium py-3 px-4 rounded-lg transition-all duration-200"
            >
              Batal
            </button>
            <button
              type="submit"
              disabled={isLoading}
              className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-4 rounded-lg transition-all duration-200 flex items-center justify-center gap-2 shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading && <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />}
              <Save className="h-4 w-4" />
              {isLoading ? 'Menyimpan...' : donation ? 'Update' : 'Tambah Donasi'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default DonationForm;